version: '3.7'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./web/dist/frontend_cryo:/usr/share/nginx/html
    ports:
      - 80:80
    networks:
      - cryoNet

  db:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/test_cryo
    networks:
      - cryoNet

  api:
    build: ./api
    volumes:
      - ./api:/app
    environment:
      - NEO4J_URI=neo4j://db:7687
      - NEO4J_PASSWORD=test_cpa
    depends_on:
      - db
    networks:
      - cryoNet


networks:
  cryoNet: